site_name: 'Urunium.Redux API'
site_url: http://uruniumredux.readthedocs.io/en/latest
docs_dir: './src/Urunium.Redux/Docs/'
google_analytics:  ['UA-55719395-2', 'uruniumredux.readthedocs.io']
pages:
    - 'Home': 'index.md'
    - 'Api': 'Urunium.Redux.md'
markdown_extensions:
  - meta
